### ISSUE TITLE
Participant List and Classroom Info

### ISSUE THREAD

**Issue by Henry-YSLin** [CSCI3100-B5/Classroom-Interchat#43]
- [x] Classroom Info (realtime updating)
- [x] Participant list (realtime updating)
- [x] Kick participant
- [x] Mute participant
- [x] Mute classroom
- [x] Request instructor permission
- [x] Promote participant to instructor

**Comment by alexkkm** [comment]
doing rquest instructor prmission

**Comment by Henry-YSLin** [comment]
Done
